dataset_builder: &ds_builder
    table_path: 'ocRnn/core/model/table.txt'
    # If change image height(32), change the net.
    # If image width is not null, the image will be distorted.
    img_shape: [32, null, 3]
    # The image that width greater than max img_width will be dropped.
    # Only work with image width is null.
    max_img_width: 500
    ignore_case: true

train:
    dataset_builder:
        <<: *ds_builder
    train_ann_paths:
        - 'data/train/train.txt'
        - 'data/eval/eval.txt'
    val_ann_paths:
        - 'data/test/test.txt'
    batch_size_per_replica: 32
    # The model for restore, even if the number of characters is different
    restore: ''
    learning_rate: 0.001
    # Number of epochs to train.
    epochs: 100
    # Reduce learning rate when a metric has stopped improving.
    # ReduceLROnPlateau Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ReduceLROnPlateau#arguments
    reduce_lr:
        factor: 0.5
        patience: 5
        min_lr: 0.0001
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0

eval:
    dataset_builder:
        <<: *ds_builder
    ann_paths:
        - 'data/test/test.txt'
    batch_size: 32
