# Generated by Django 3.1.7 on 2021-04-16 23:27

import datetime
from django.db import migrations, models
import ocRnn.file_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[ocRnn.file_validator.validate_file_extension])),
                ('text', models.CharField(default='Undefined', max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('processing_time', models.CharField(default='0 seconds', max_length=15)),
            ],
        ),
    ]
